export enum EntityColumnName {
  ID = 'id',
  CREATED_AT = 'created_at',
  UPDATED_AT = 'updated_at',
  EMAIL = 'email',
  PASSWORD = 'password',
  NAME = 'name',
  ROLE = 'role',
  IS_VERIFIED = 'is_verified',
  PHONE_NUMBER = 'phone_number',
  PRICE = 'price',
  CATEGORY_ID = 'category_id',
  RESTAURANT = 'restaurant',
  RESTAURANT_ID = 'restaurant_id',
  PATH = 'path',
  IMAGE_ID = 'image_id',
  NUMBER = 'number',
  STATUS = 'status',
}
