export enum HttpExceptionMessageKey {
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  USER_WITH_THIS_EMAIL_DOES_NOT_EXIST = 'USER_WITH_THIS_EMAIL_DOES_NOT_EXIST',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_IS_NOT_VERIFIED_YET = 'USER_IS_NOT_VERIFIED_YET',
  DB_INPUT_ERROR = 'INVALID_DB_INPUTS',
  INVALID_ID = 'INVALID_ID',
  TABLE_WITH_SAME_NAME_ALREADY_EXISTS = 'TABLE_WITH_SAME_NAME_ALREADY_EXISTS',
}
